name: TDD Tests with GitHub Actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          yarn-version: '1.22.15'
      - run: cd ./client/
      - run: yarn install
      - run: cd ..
      - run: yarn test
